version: "2"
services:
  dynamodb:
    image: hilverd/dynamodb
    network_mode: bridge
    ports:
      - "8000:8000"
      - "4567:4567"
    mem_limit: 2G
    container_name: dynamodb

  gremlin-http:
    image: registry.devshift.net/bayesian/gremlin
    network_mode: bridge
    entrypoint: /bin/entrypoint-local.sh
    environment:
      - REST=1
      - DEBUG_GRAPH_METRICS=0
    ports:
      - "8181:8182"
    depends_on:
      - dynamodb
    mem_limit: 2G
    container_name: bayesian-gremlin-http
    links:
      - dynamodb
